export const TAG_DATA = [
  { id: 1, tag: "Python" },
  { id: 2, tag: "AWS" },
  { id: 3, tag: "React" },
  { id: 4, tag: "TypeScript" },
  { id: 5, tag: "JavaScript" },
  { id: 6, tag: "Flutter" },
  { id: 7, tag: "Next.js" },
  { id: 8, tag: "Docker" },
  { id: 9, tag: "Go" },
  { id: 10, tag: "Rails" },
  { id: 11, tag: "GitHub" },
  { id: 12, tag: "Ruby" },
  { id: 13, tag: "PHP" },
  { id: 14, tag: "Rust" },
  { id: 15, tag: "IOS" },
  { id: 16, tag: "Linux" },
  { id: 17, tag: "Swift" },
  { id: 18, tag: "Android" },
  { id: 19, tag: "Node.js" },
  { id: 20, tag: "Unity" },
  { id: 21, tag: "Git" },
  { id: 22, tag: "VS Code" },
  { id: 23, tag: "CSS" },
  { id: 24, tag: "Dart" },
  { id: 25, tag: "Laravel" },
  { id: 26, tag: "Firebase" },
  { id: 27, tag: "GCP" },
  { id: 28, tag: "Java" },
  { id: 29, tag: "ChatGPT" },
  { id: 30, tag: "GitHub Actions" },
  { id: 31, tag: "Azure" },
  { id: 32, tag: "AtCoder" },
  { id: 33, tag: "HTML" },
  { id: 34, tag: "C#" },
  { id: 35, tag: "macOS" },
  { id: 36, tag: "Vue.js" },
  { id: 37, tag: "Windows" },
  { id: 38, tag: "AI" },
  { id: 39, tag: "Kubernetes" },
  { id: 40, tag: "Terraform" },
  { id: 41, tag: "Web" },
  { id: 42, tag: "MySQL" },
  { id: 43, tag: "Kotlin" },
  { id: 44, tag: "Ubuntu" },
  { id: 45, tag: "API" },
  { id: 46, tag: "Test" },
  { id: 47, tag: "GraphQL" },
  { id: 48, tag: "SwiftUI" },
  { id: 49, tag: "SQL" },
  { id: 50, tag: "C++" },
  { id: 51, tag: "Lambda" },
  { id: 52, tag: "Tailwind CSS" },
  { id: 53, tag: "Security" },
  { id: 54, tag: "frontend" },
  { id: 55, tag: "backend" },
  { id: 56, tag: "Vim" },
  { id: 57, tag: "Slack" },
  { id: 58, tag: "OpenAI" },
  { id: 59, tag: "Soft Skill" },
  { id: 60, tag: "회고" },
];
