import Head from "next/head";
import useInputValue from "../../hooks/useInputValue";
import { useRouter } from "next/router";
import axios from "axios";
import Nav from "../../components/Nav/Nav";
import { useEffect, useState } from "react";
import React from "react";
import Tag from "../../components/common/Tag";
import { EditInputValueType } from "../../types/post";
//

export default function Edit() {
  const [initInputValue, setInitInputValue] = useState<EditInputValueType>({
    title: "",
    texts: "",
    tag: "",
  });

  const { inputValue, setInputValue, handleInput } =
    useInputValue(initInputValue);
  const [tags, setTags] = useState<string[]>([]);

  const router = useRouter();
  const { id } = router.query;
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;

  useEffect(() => {
    if (id) {
      axios
        .get(
          `${baseUrl}/post/${id}`

          // {
          //   Authorization: `Bearer ${"토큰"}`,
          // }
        )
        .then((data) => {
          if (data.status === 200) {
            const postData = data.data;
            const namesArray = postData.hashTags.map((item) => item.name);
            setTags(namesArray);
            setInitInputValue({
              title: postData.title,
              texts: postData.content,
              tag: "",
            });
          } else if (data.status === 400) {
            alert("다시 확인해주세요.");
          }
        })
        .catch((error) => {
          console.log(error);
        });
    }
  }, [id]);

  const editPost = () => {
    axios
      .put(
        `${baseUrl}/post/${id}`,
        {
          title: inputValue.title,
          content: inputValue.texts,
          hashTags: tags.join(""),
        }
        // {
        //   Authorization: `Bearer ${"토큰"}`,
        // }
      )
      .then((data) => {
        if (data.status === 200) {
          router.push("/");
        } else if (data.status === 400) {
          alert("다시 확인해주세요.");
        }
      })
      .catch((error) => {
        console.log(error);
      });
  };

  const titleValid =
    inputValue.title.length > 0 && inputValue.title.length <= 20;
  const textsValid = inputValue.texts.length > 10;
  const postValid = titleValid && textsValid;

  const makeTag = (e) => {
    const completedTag = "#" + inputValue.tag;

    if (e.key === "Enter" && inputValue.tag !== "") {
      if (tags.length < 3) {
        if (!tags.includes(completedTag)) {
          setTags([...tags, completedTag]);
          setInputValue({ ...inputValue, tag: "" });
        } else {
          alert("중복된 태그입니다.");
          setInputValue({ ...inputValue, tag: "" });
        }
      } else if (tags.length >= 3) {
        alert("태그는 최대 3개만 작성할 수 있어요.");
        setInputValue({ ...inputValue, tag: "" });
      }
    }
  };

  const handleFormSubmit = (e) => {
    e.preventDefault();
  };

  const removeTag = (idx) => {
    const confirmation = window.confirm("태그를 삭제하시겠습니까?");

    if (confirmation) {
      const updatedTags = tags.filter((_, i) => i !== idx);
      setTags(updatedTags);
    }
  };

  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid place-items-center gap-4 p-4">
        <Nav postWriting={editPost} isWriting />
        <div className="grid w-width60">
          <input
            name="title"
            placeholder="제목"
            maxLength={20}
            minLength={0}
            required
            onChange={handleInput}
            defaultValue={initInputValue.title}
            className="p-8 my-4 mx-0 h-8 border border-solid border-white rounded-lg text-2xl shadow-shadow200"
          ></input>
          <textarea
            name="texts"
            minLength={10}
            required
            placeholder="내용을 입력해주세요."
            onChange={handleInput}
            defaultValue={initInputValue.texts}
            className="h-height40 resize-none overflow-x-hidden overflow-y-scroll border border-solid border-white rounded-xl8 p-8 text-2xl shadow-shadow200"
          ></textarea>
          <form
            typeof="submit"
            onSubmit={handleFormSubmit}
            className="p-8 my-4 mx-0 h-8 border border-solid border-white rounded-lg text-2xl shadow-shadow200 flex items-center gap-2 bg-white"
          >
            {tags.map((tag, idx) => {
              return (
                <Tag
                  key={idx}
                  isWriting
                  removeTag={removeTag}
                  tag={tag}
                  tagId={idx}
                />
              );
            })}

            <input
              type="text"
              className="border-0 focus:outline-none"
              name="tag"
              placeholder={tags.length < 3 ? "태그를 입력해보세요." : ""}
              required
              onChange={(e) => handleInput(e)}
              onKeyUp={(e) => makeTag(e)}
              value={inputValue.tag}
            ></input>
          </form>
        </div>
      </main>
    </>
  );
}
