import Head from "next/head";
import style from "../../styles/main.module.css";

import React, { useState } from "react";

import { useRecoilState } from "recoil";
import { idState, savedPostState } from "../../store/savePostStore";
import Nav from "../../components/Nav/Nav";
import Item from "../../components/common/Item/Item";
import FilterBar from "../../components/Filter/filterBar";
import FilterModal from "../../components/Filter";

export default function Like() {
  const savedPosts = useRecoilState(savedPostState);
  const postList = savedPosts[0];
  const [isSearch, setIsSearch] = useState(false);

  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.main}>
        <Nav onclick={null} />
        <FilterBar onclick={() => setIsSearch(!isSearch)} />
        {isSearch && <FilterModal />}

        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {postList.map((item, idx) => {
            return (
              <Item
                onFetchMore={() => console.log(1)}
                isLastItem={postList.length - 1 === idx}
                key={item.id}
                {...item}
              />
            );
          })}
        </div>

        {/* {!isLastItem && <div>loading</div>} */}
      </div>
    </>
  );
}
