import Head from "next/head";
import style from "../../styles/main.module.css";
import React from "react";
import Nav from "../../components/Nav/Nav";
import NonMemberLike from "./nonMember";
import MemberLike from "./member";

export default function Like() {
  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.main}>
        <Nav />
        {/* <MemberLike /> */}
        <NonMemberLike />
      </div>
    </>
  );
}
