import Head from "next/head";
import { Inter } from "next/font/google";
//

const inter = Inter({ subsets: ["latin"] });

const Main = () => {
  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.main}></div>
    </>
  );
};

export default Main;
