import Head from "next/head";
import style from "../styles/main.module.css";
import Item from "../components/common/Item/Item";
import { useEffect, useState } from "react";
import axios from "axios";
import Nav from "../components/Nav/Nav";
import React from "react";
//

export default function Main() {
  const [itemListData, setItemListData] = useState([]);

  useEffect(() => {
    axios
      // .get("/data/MAIN_LIST_DATA.json")
      .get("https://api.falsystack.jp/posts")
      .then((data) => {
        setItemListData(data.data);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.main}>
        <Nav onclick={null} />
        {itemListData.map((item) => {
          return (
            <Item
              key={item.id}
              id={item.id}
              img={item.img}
              title={item.title}
              content={item.content}
              author={item.author}
              heartNum={item.heartNum}
            />
          );
        })}
      </div>
    </>
  );
}
