import Head from "next/head";
import style from "./detail.module.css";
import axios from "axios";
import Nav from "../../components/Nav/Nav";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Tag from "../../components/common/Tag";
//

type postingDataType = {
  id: number;
  title: string;
  content: string;
  author: string;
  hashTags: [{ id: number; name: string }];
  createdAt: string;
};

const initialPostingData: postingDataType = {
  id: 0,
  title: "",
  content: "",
  author: "",
  hashTags: [{ id: 0, name: "" }],
  createdAt: "",
};

export default function Detail() {
  const router = useRouter();
  const { id } = router.query;
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;

  const [postingData, setPostingData] =
    useState<postingDataType>(initialPostingData);
  const { title, content, author, hashTags, createdAt } = postingData;

  useEffect(() => {
    if (id) {
      axios
        .get(
          `${baseUrl}/post/${id}`

          // {
          //   Authorization: `Bearer ${"토큰"}`,
          // }
        )
        .then((data) => {
          if (data.status === 200) {
            setPostingData(data.data);
          } else if (data.status === 400) {
            alert("다시 확인해주세요.");
          }
        })
        .catch((error) => {
          console.log(error);
        });
    }
  }, [id]);

  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={style.container}>
        <Nav onclick={null} />
        <div className={style.all}>
          <header className={style.titleContainer}>
            <h1 className={style.header}>{title}</h1>
            <div className={style.postData}>
              <p className={style.text}>@ {author}</p>
              <p className={style.text}>{createdAt.slice(0, 10)}</p>
            </div>
          </header>
          <main className={style.main}>
            <div className={style.tagContainer}>
              {hashTags.length > 0 &&
                hashTags.map((tag) => {
                  return <Tag key={tag.id} tag={tag.name} id={tag.id} />;
                })}
            </div>
            <article className={style.article}>{content}</article>
          </main>
        </div>
      </div>
    </>
  );
}
