import Head from "next/head";
import { Inter } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faImage } from "@fortawesome/free-regular-svg-icons";
import style from "./writing.module.css";
//

const inter = Inter({ subsets: ["latin"] });

const Writing = () => {
  return (
    <>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.main}>
        <nav className={style.nav}>
          <button className={style.btn}>Home</button>
          <div className={style.navCenter}>
            <label for="file">
              <FontAwesomeIcon className={style.imgIcon} icon={faImage} />
            </label>
            <input
              id="file"
              type="file"
              value="file"
              className={style.file}
            ></input>

            <select className={style.select}>
              <option defaultValue>글씨 크기</option>
              <option>10</option>
              <option>20</option>
              <option>30</option>
            </select>
            <select className={style.select}>
              <option defaultValue>글씨 모양</option>
              <option>일반</option>
              <option>강조</option>
              <option>옆으로</option>
              <option>밑줄</option>
              <option>가운데줄</option>
            </select>
            <select className={style.select}>
              <option defaultValue>글씨 정렬</option>
              <option>오른쪽</option>
              <option>왼쪽</option>
              <option>가운데</option>
            </select>
          </div>

          <button className={style.btn}>마이페이지</button>
        </nav>
        <main className={style.mainContainer}>
          <select className={style.select}>
            <option defaultValue>카테고리</option>
            <option>여행</option>
            <option>개발</option>
            <option>요리</option>
          </select>
          <input placeholder="제목" className={style.title}></input>
          <textarea className={style.texts}></textarea>
        </main>
        <button className={style.submitBtn}>완료</button>
      </div>
    </>
  );
};

export default Writing;
